language: python

python:
  - "3.6"

branches:
  only:
    - master

env:
  - TOXENV=py27-lint
  - TOXENV=py27-django110
  - TOXENV=py27-django111
  - TOXENV=py36-django110
  - TOXENV=py36-django111
  - TOXENV=py36-django2

install:
  - pip install tox

script:
  - tox -e $TOXENV

after_success:
  - pip install codecov
  - codecov -e TOXENV
