language: python

python:
  - "2.7"
  - "3.6"
  - "3.7"

branches:
  only:
    - master

env:
  - TOXENV=py27-lint
  - TOXENV=py27-django111
  - TOXENV=py36-django111
  - TOXENV=py36-django2
  - TOXENV=py36-django21
  - TOXENV=py36-django22
  - TOXENV=py37-django111
  - TOXENV=py37-django2
  - TOXENV=py37-django21
  - TOXENV=py37-django22

install:
  - pip install tox

script:
  - tox -e $TOXENV

after_success:
  - pip install codecov
  - codecov -e TOXENV
